version: '3.9'
services:
  db:
    image: postgres:15
    container_name: survey-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surveydb
    ports:
    - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data
    networks:
    - survey-net
  backend:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: survey-backend
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/surveydb
      QUARKUS_HTTP_PORT: 8080
    depends_on:
    - db
    ports:
    - 8080:8080
    networks:
    - survey-net
volumes:
  db_data: null
networks:
  survey-net:
    driver: bridge